# Site settings
title: 自由灯塔
header-img: img/bg1.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "http://ymyqwe.github.io/blog/"
url: "http://ymyqwe.github.io/blog/"

# SNS settings
RSS: false
weibo_username: maniaU
zhihu_username: maniaU
twitter_username: ymyymy_2@hotmail.com
github_username:  ymyqwe
#facebook_username:  ymyymy_2@hotmail.com

# Build settings
markdown: kramdown
input: GFM
highlighter: pygments

paginate: 5
paginate_path: "/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "高山仰止 景行行止"
sidebar-avatar: /img/lighthouse-sky.png     # use absolute URL, seeing it's used in both `/` and `/about/`


